# !/usr/bin/python3
# -*- coding: UTF-8 -*-
import urllib.request


def download5(url, free_proxy=None, user_agent='test', num_retries=2, data=None):
    headers = {
                  "Accept": "text / html, application / xhtml + xml, application / xml;q = 0.9, image / webp, * / *;q = 0.8",
                  # "Accept-Encoding": "gzip, deflate",
                  "Accept - Language": "zh - CN, zh;q = 0.8, en - us;q = 0.6, en;q = 0.5;q = 0.4",
                  "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 micromessage/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.901.400 QQBrowser/9.0.2524.400"}
    request = urllib.request.Request(url, data, headers=headers)
    opener = urllib.request.build_opener()
    if free_proxy:
        proxy_params = {urllib.request.urlparse(url).scheme: free_proxy}
        opener.add_handler(urllib.request.ProxyHandler(proxy_params))
    try:
        html5 = opener.open(request).read()
    except urllib.request.URLError as e:
        print("download error", e.reason)
        html5 = None
        if num_retries > 0:
            if hasattr(e, 'code') and 500 <= e.code < 600:
                html5 = download5(url, free_proxy, user_agent, num_retries - 1)
    return html5
url = 'http://wx.sephora.cn/index.php?m=Nearby&a=index&provinceid=2&cityid=500'
html = download5(url)

print(html)

# url = {'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-0.json':'北京市北京市东城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-1.json':'北京市北京市西城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-2.json':'北京市北京市朝阳区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-3.json':'北京市北京市丰台区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-4.json':'北京市北京市石景山区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-5.json':'北京市北京市海淀区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-6.json':'北京市北京市门头沟区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-7.json':'北京市北京市房山区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-8.json':'北京市北京市通州区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-9.json':'北京市北京市顺义区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-10.json':'北京市北京市昌平区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-11.json':'北京市北京市大兴区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-12.json':'北京市北京市宣武区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-13.json':'北京市北京市密云区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-14.json':'北京市北京市密云县',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-15.json':'北京市北京市怀柔区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-0-0-16.json':'北京市北京市平谷区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-1-0-0.json':'天津市天津市河西区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-1-0-1.json':'天津市天津市河北区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-1-0-2.json':'天津市天津市西青区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-1-0-3.json':'天津市天津市津南区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-1-0-4.json':'天津市天津市和平区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-1-0-5.json':'天津市天津市滨海新区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-1-0-6.json':'天津市天津市塘沽区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-1-0-7.json':'天津市天津市河东区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-1-0-8.json':'天津市天津市红桥区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-1-0-9.json':'天津市天津市东丽区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-1-0-10.json':'天津市天津市南开区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-2-0-0.json':'上海市上海市黄浦区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-2-0-1.json':'上海市上海市徐汇区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-2-0-2.json':'上海市上海市长宁区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-2-0-3.json':'上海市上海市静安区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-2-0-4.json':'上海市上海市普陀区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-2-0-5.json':'上海市上海市闸北区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-2-0-6.json':'上海市上海市虹口区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-2-0-7.json':'上海市上海市闵行区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-2-0-8.json':'上海市上海市浦东新区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-2-0-9.json':'上海市上海市青浦区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-2-0-10.json':'上海市上海市杨浦区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-2-0-11.json':'上海市上海市松江区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-2-0-12.json':'上海市上海市宝山区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-2-0-13.json':'上海市上海市自由贸易试验区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-2-0-14.json':'上海市上海市嘉定区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-0-0.json':'江苏省南京市秦淮区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-0-1.json':'江苏省南京市玄武区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-0-2.json':'江苏省南京市浦口区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-0-3.json':'江苏省南京市江宁区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-0-4.json':'江苏省南京市建邺区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-0-5.json':'江苏省南京市雨花台区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-0-6.json':'江苏省南京市栖霞区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-0-7.json':'江苏省南京市白下区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-0-8.json':'江苏省南京市鼓楼区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-1-0.json':'江苏省苏州市虎丘区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-1-1.json':'江苏省苏州市姑苏区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-1-2.json':'江苏省苏州市平江区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-1-3.json':'江苏省苏州市工业园区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-1-4.json':'江苏省苏州市高新区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-1-5.json':'江苏省苏州市金阊区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-1-6.json':'江苏省苏州市吴中区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-1-7.json':'江苏省苏州市相城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-1-8.json':'江苏省苏州市吴江区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-1-9.json':'江苏省苏州市昆山市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-2-0.json':'江苏省无锡市高新区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-2-1.json':'江苏省无锡市崇安区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-2-2.json':'江苏省无锡市锡山经济开发区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-2-3.json':'江苏省无锡市惠山区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-2-4.json':'江苏省无锡市南长区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-2-5.json':'江苏省无锡市滨湖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-3-0.json':'江苏省常州市钟楼区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-3-1.json':'江苏省常州市武进区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-3-2.json':'江苏省常州市天宁区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-4-0.json':'江苏省南通市崇川区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-5-0.json':'江苏省扬州市邗江区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-3-5-1.json':'江苏省扬州市广陵区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-0-0.json':'浙江省杭州市上城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-0-1.json':'浙江省杭州市下城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-0-2.json':'浙江省杭州市江干区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-0-3.json':'浙江省杭州市西湖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-0-4.json':'浙江省杭州市萧山区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-0-5.json':'浙江省杭州市余杭区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-0-6.json':'浙江省杭州市拱墅区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-0-7.json':'浙江省杭州市经济技术开发区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-0-8.json':'浙江省杭州市滨江区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-1-0.json':'浙江省宁波市鄞州区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-1-1.json':'浙江省宁波市海曙区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-1-2.json':'浙江省宁波市江北区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-1-3.json':'浙江省宁波市江东区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-1-4.json':'浙江省宁波市余姚市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-1-5.json':'浙江省宁波市奉化区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-2-0.json':'浙江省绍兴市越城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-2-1.json':'浙江省绍兴市柯桥区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-4-3-0.json':'浙江省嘉兴市南湖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-0-0.json':'江西省南昌市西湖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-0-1.json':'江西省南昌市红谷滩新区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-0-2.json':'江西省南昌市东湖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-0-3.json':'江西省南昌市青云谱区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-0-4.json':'江西省南昌市青山湖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-0-5.json':'江西省南昌市南昌县',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-0-6.json':'江西省南昌市新建县',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-0-7.json':'江西省南昌市进贤县',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-0-8.json':'江西省南昌市昌北区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-0-9.json':'江西省南昌市新建区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-0-10.json':'江西省南昌市高新技术产业开发区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-1-0.json':'江西省九江市濂溪区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-1-1.json':'江西省九江市经济技术开发区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-1-2.json':'江西省九江市浔阳区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-2-0.json':'江西省萍乡市安源区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-3-0.json':'江西省宜春市袁州区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-4-0.json':'江西省新余市渝水区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-5-5-0.json':'江西省上饶市信州区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-6-0-0.json':'河南省郑州市金水区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-6-0-1.json':'河南省郑州市管城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-6-0-2.json':'河南省郑州市二七区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-6-0-3.json':'河南省郑州市郑东新区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-6-0-4.json':'河南省郑州市中原区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-6-0-5.json':'河南省郑州市航空港区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-6-0-6.json':'河南省郑州市新郑市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-6-0-7.json':'河南省郑州市惠济区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-6-1-0.json':'河南省新乡市卫滨区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-6-2-0.json':'河南省许昌市魏都区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-6-3-0.json':'河南省洛阳市涧西区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-6-3-1.json':'河南省洛阳市洛龙区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-6-3-2.json':'河南省洛阳市西工区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-6-4-0.json':'河南省开封市辖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-6-5-0.json':'河南省驻马店市驿城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-0-0.json':'湖北省武汉市武昌区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-0-1.json':'湖北省武汉市洪山区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-0-2.json':'湖北省武汉市汉阳区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-0-3.json':'湖北省武汉市江岸区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-0-4.json':'湖北省武汉市江汉区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-0-5.json':'湖北省武汉市硚口区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-0-6.json':'湖北省武汉市青山区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-0-7.json':'湖北省武汉市东西湖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-0-8.json':'湖北省武汉市汉南区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-0-9.json':'湖北省武汉市蔡甸区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-0-10.json':'湖北省武汉市江夏区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-0-11.json':'湖北省武汉市黄陂区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-0-12.json':'湖北省武汉市新洲区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-1-0.json':'湖北省黄石市市辖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-1-1.json':'湖北省黄石市黄石港区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-2-0.json':'湖北省十堰市市辖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-2-1.json':'湖北省十堰市茅箭区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-2-2.json':'湖北省十堰市张湾区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-3-0.json':'湖北省宜昌市市辖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-3-1.json':'湖北省宜昌市西陵区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-3-2.json':'湖北省宜昌市伍家岗区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-3-3.json':'湖北省宜昌市宜都市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-3-4.json':'湖北省宜昌市枝江市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-3-5.json':'湖北省宜昌市远安县',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-3-6.json':'湖北省宜昌市当阳市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-4-0.json':'湖北省襄阳市市辖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-4-1.json':'湖北省襄阳市高新区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-4-2.json':'湖北省襄阳市樊城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-4-3.json':'湖北省襄阳市枣阳市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-4-4.json':'湖北省襄阳市谷城县',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-4-5.json':'湖北省襄阳市襄城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-5-0.json':'湖北省鄂州市市辖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-5-1.json':'湖北省鄂州市鄂城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-6-0.json':'湖北省荆门市荆门市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-6-1.json':'湖北省荆门市市辖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-6-2.json':'湖北省荆门市钟祥市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-7-0.json':'湖北省孝感市孝南区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-7-1.json':'湖北省孝感市云梦县',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-7-2.json':'湖北省孝感市安陆市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-7-3.json':'湖北省孝感市汉川市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-7-4.json':'湖北省孝感市大悟县',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-7-5.json':'湖北省孝感市应城市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-8-0.json':'湖北省荆州市市辖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-8-1.json':'湖北省荆州市沙市区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-8-2.json':'湖北省荆州市荆州区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-8-3.json':'湖北省荆州市洪湖市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-8-4.json':'湖北省荆州市东宝区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-9-0.json':'湖北省黄冈市黄州区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-9-1.json':'湖北省黄冈市红安县',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-9-2.json':'湖北省黄冈市武穴市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-10-0.json':'湖北省咸宁市咸安区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-10-1.json':'湖北省咸宁市崇阳县',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-10-2.json':'湖北省咸宁市嘉鱼县',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-11-0.json':'湖北省随州市曾都区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-11-1.json':'湖北省随州市广水市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-12-0.json':'湖北省省直辖县级行政区划仙桃市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-12-1.json':'湖北省省直辖县级行政区划潜江市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-12-2.json':'湖北省省直辖县级行政区划天门市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-13-0.json':'湖北省恩施市舞阳坝街道',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-13-1.json':'湖北省恩施市恩施',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-14-0.json':'湖北省仙桃市仙桃市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-7-15-0.json':'湖北省天门市天门市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-0-0.json':'湖南省长沙市芙蓉区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-0-1.json':'湖南省长沙市天心区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-0-2.json':'湖南省长沙市岳麓区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-0-3.json':'湖南省长沙市开福区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-0-4.json':'湖南省长沙市雨花区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-0-5.json':'湖南省长沙市长沙县',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-0-6.json':'湖南省长沙市高新开区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-0-7.json':'湖南省长沙市黄花镇',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-0-8.json':'湖南省长沙市高新开发区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-1-0.json':'湖南省株洲市芦淞区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-1-1.json':'湖南省株洲市荷塘区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-1-2.json':'湖南省株洲市天元区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-2-0.json':'湖南省湘潭市雨湖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-2-1.json':'湖南省湘潭市雨花区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-3-0.json':'湖南省益阳市赫山区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-3-1.json':'湖南省益阳市赫山市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-4-0.json':'湖南省衡阳市蒸湘区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-4-1.json':'湖南省衡阳市雁峰区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-8-4-2.json':'湖南省衡阳市石鼓区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-0-0.json':'广东省广州市荔湾区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-0-1.json':'广东省广州市越秀区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-0-2.json':'广东省广州市海珠区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-0-3.json':'广东省广州市天河区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-0-4.json':'广东省广州市白云区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-0-5.json':'广东省广州市番禺区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-0-6.json':'广东省广州市花都区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-1-0.json':'广东省深圳市罗湖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-1-1.json':'广东省深圳市福田区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-1-2.json':'广东省深圳市南山区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-1-3.json':'广东省深圳市宝安区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-1-4.json':'广东省深圳市龙岗区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-1-5.json':'广东省深圳市龙华新区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-1-6.json':'广东省深圳市深圳市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-1-7.json':'广东省深圳市坪山区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-1-8.json':'广东省深圳市龙华区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-2-0.json':'广东省东莞市长安镇',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-2-1.json':'广东省东莞市东城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-2-2.json':'广东省东莞市莞城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-2-3.json':'广东省东莞市虎门镇',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-2-4.json':'广东省东莞市万江区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-2-5.json':'广东省东莞市南城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-2-6.json':'广东省东莞市常平镇',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-2-7.json':'广东省东莞市麻涌镇',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-2-8.json':'广东省东莞市厚街镇',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-2-9.json':'广东省东莞市寮步镇',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-2-10.json':'广东省东莞市石龙镇',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-2-11.json':'广东省东莞市凤岗镇',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-3-0.json':'广东省佛山市禅城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-3-1.json':'广东省佛山市南海区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-3-2.json':'广东省佛山市三水区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-4-0.json':'广东省惠州市惠城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-4-1.json':'广东省惠州市惠阳区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-5-0.json':'广东省揭阳市空港经济区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-6-0.json':'广东省 广州市天河区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-9-7-0.json':'广东省珠海市香洲区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-10-0-0.json':'重庆市重庆市渝中区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-10-0-1.json':'重庆市重庆市沙坪坝区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-10-0-2.json':'重庆市重庆市南岸区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-10-0-3.json':'重庆市重庆市巴南区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-10-0-4.json':'重庆市重庆市九龙坡区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-10-0-5.json':'重庆市重庆市江北区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-10-0-6.json':'重庆市重庆市渝北区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-10-0-7.json':'重庆市重庆市大渡口区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-10-0-8.json':'重庆市重庆市北部新区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-11-0-0.json':'四川省成都市高新区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-11-0-1.json':'四川省成都市成华区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-11-0-2.json':'四川省成都市武侯区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-11-0-3.json':'四川省成都市青羊区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-11-0-4.json':'四川省成都市金牛区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-11-0-5.json':'四川省成都市锦江区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-11-0-6.json':'四川省成都市龙泉驿区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-11-0-7.json':'四川省成都市新津县',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-11-0-8.json':'四川省成都市双流区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-11-0-9.json':'四川省成都市双流县',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-12-0-0.json':'河北省三河市燕郊高新区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-12-1-0.json':'河北省石家庄市正定县',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-12-1-1.json':'河北省石家庄市裕华区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-12-1-2.json':'河北省石家庄市桥西区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-12-1-3.json':'河北省石家庄市长安区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-12-1-4.json':'河北省石家庄市藁城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-12-1-5.json':'河北省石家庄市新华区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-12-2-0.json':'河北省廊坊市三河市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-12-3-0.json':'河北省保定市涿州市',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-12-3-1.json':'河北省保定市莲池区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-13-0-0.json':'山东省青岛市市南区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-13-0-1.json':'山东省青岛市市北区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-13-0-2.json':'山东省青岛市崂山区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-13-0-3.json':'山东省青岛市李沧区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-13-0-4.json':'山东省青岛市城阳区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-13-1-0.json':'山东省济南市天桥区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-13-1-1.json':'山东省济南市历城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-13-1-2.json':'山东省济南市市中区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-13-1-3.json':'山东省济南市历下区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-13-1-4.json':'山东省济南市槐荫区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-13-2-0.json':'山东省烟台市经济技术开发区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-13-2-1.json':'山东省烟台市芝罘区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-13-3-0.json':'山东省潍坊市潍城区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-14-0-0.json':'安徽省合肥市滨湖区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-14-0-1.json':'安徽省合肥市庐阳区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-14-0-2.json':'安徽省合肥市蜀山区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-14-0-3.json':'安徽省合肥市瑶海区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-14-0-4.json':'安徽省合肥市包河区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-15-0-0.json':'福建省厦门市思明区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-15-0-1.json':'福建省厦门市湖里区',
# 'http://www.zhouheiya.cn/wcs/Tpl/home/default/storejson/0-15-0-2.json':'福建省厦门市自由贸易试验区'
# }
#
# f = open('zou_hei_ya180727-1.txt', "w+", encoding="utf-8")
# for k, v in url.items():
#     html = download5(k)
#     # print(type(html))
#     # print(html)
#     html = str(html).replace('[[', '[')
#     html = str(html).replace('[', '["'+v+'",')
#     f.write(html)
#     f.write(',')
# f.close()
