import urllib.request
import json
from time import sleep


def download5(url, free_proxy=None, user_agent='test', num_retries=2, data=None):
    # print("download5...", url)
    # 设置headers 中的用户代理，默认值是test
    headers = {"User_agent": user_agent}
    # 将用户代理添加到请求中
    request = urllib.request.Request(url, data, headers=headers)
    # 创建句柄
    opener = urllib.request.build_opener()
    # 判断如果proxy是否有值
    if free_proxy:
        # 获取ip代理协议和IP代理
        proxy_params = {urllib.request.urlparse(url).scheme: free_proxy}
        # 将IP代理设置添加到句柄中
        opener.add_handler(urllib.request.ProxyHandler(proxy_params))
    try:
        # 使用句柄的open()打开网页，read()读取内容
        html5 = opener.open(request).read()
    # 异常处理，捕获异常
    except urllib.request.URLError as e:
        # 打印异常原因
        print("download error", e.reason)
        html5 = None
        # 判断重新加载次数是否大于0
        if num_retries > 0:
            # 判断 页面code是否在500和600之间
            if hasattr(e, 'code') and 500 <= e.code < 600:
                # 调用自身
                html5 = download5(url, free_proxy, user_agent, num_retries - 1)
    return html5.decode('utf-8')


url = [




       'https://tnfcms.blue-dot.cn/api/location/city/206',
       'https://tnfcms.blue-dot.cn/api/location/city/207',
       'https://tnfcms.blue-dot.cn/api/location/city/208',
       'https://tnfcms.blue-dot.cn/api/location/city/209',
       'https://tnfcms.blue-dot.cn/api/location/city/210',
       'https://tnfcms.blue-dot.cn/api/location/city/211',
       'https://tnfcms.blue-dot.cn/api/location/city/212',
       'https://tnfcms.blue-dot.cn/api/location/city/213',
       'https://tnfcms.blue-dot.cn/api/location/city/214',
       'https://tnfcms.blue-dot.cn/api/location/city/215',
       'https://tnfcms.blue-dot.cn/api/location/city/216',
       'https://tnfcms.blue-dot.cn/api/location/city/217',
       'https://tnfcms.blue-dot.cn/api/location/city/218',
       'https://tnfcms.blue-dot.cn/api/location/city/219',
       'https://tnfcms.blue-dot.cn/api/location/city/220',
       'https://tnfcms.blue-dot.cn/api/location/city/221',
       'https://tnfcms.blue-dot.cn/api/location/city/222',
       'https://tnfcms.blue-dot.cn/api/location/city/223',
       'https://tnfcms.blue-dot.cn/api/location/city/224',
       'https://tnfcms.blue-dot.cn/api/location/city/225',
       'https://tnfcms.blue-dot.cn/api/location/city/226',
       'https://tnfcms.blue-dot.cn/api/location/city/227',
       'https://tnfcms.blue-dot.cn/api/location/city/228',
       'https://tnfcms.blue-dot.cn/api/location/city/229',
       'https://tnfcms.blue-dot.cn/api/location/city/230',
       'https://tnfcms.blue-dot.cn/api/location/city/231',
       'https://tnfcms.blue-dot.cn/api/location/city/232',
       'https://tnfcms.blue-dot.cn/api/location/city/233',
       'https://tnfcms.blue-dot.cn/api/location/city/234',
       'https://tnfcms.blue-dot.cn/api/location/city/235',
       'https://tnfcms.blue-dot.cn/api/location/city/236',
       'https://tnfcms.blue-dot.cn/api/location/city/237',
       'https://tnfcms.blue-dot.cn/api/location/city/238',
       'https://tnfcms.blue-dot.cn/api/location/city/239',
       'https://tnfcms.blue-dot.cn/api/location/city/240',
       'https://tnfcms.blue-dot.cn/api/location/city/241',
       'https://tnfcms.blue-dot.cn/api/location/city/242',
       'https://tnfcms.blue-dot.cn/api/location/city/243',
       'https://tnfcms.blue-dot.cn/api/location/city/244',
       'https://tnfcms.blue-dot.cn/api/location/city/245',
       'https://tnfcms.blue-dot.cn/api/location/city/246',
       'https://tnfcms.blue-dot.cn/api/location/city/247',
       'https://tnfcms.blue-dot.cn/api/location/city/248',
       'https://tnfcms.blue-dot.cn/api/location/city/249',
       'https://tnfcms.blue-dot.cn/api/location/city/250',
       'https://tnfcms.blue-dot.cn/api/location/city/251',
       'https://tnfcms.blue-dot.cn/api/location/city/252',
       'https://tnfcms.blue-dot.cn/api/location/city/253',
       'https://tnfcms.blue-dot.cn/api/location/city/254',
       'https://tnfcms.blue-dot.cn/api/location/city/255',
       'https://tnfcms.blue-dot.cn/api/location/city/256',
       'https://tnfcms.blue-dot.cn/api/location/city/257',
       'https://tnfcms.blue-dot.cn/api/location/city/258',
       'https://tnfcms.blue-dot.cn/api/location/city/259',
       'https://tnfcms.blue-dot.cn/api/location/city/260',
       'https://tnfcms.blue-dot.cn/api/location/city/261',
       'https://tnfcms.blue-dot.cn/api/location/city/262',
       'https://tnfcms.blue-dot.cn/api/location/city/263',
       'https://tnfcms.blue-dot.cn/api/location/city/264',
       'https://tnfcms.blue-dot.cn/api/location/city/265',
       'https://tnfcms.blue-dot.cn/api/location/city/266',
       'https://tnfcms.blue-dot.cn/api/location/city/267',
       'https://tnfcms.blue-dot.cn/api/location/city/268',
       'https://tnfcms.blue-dot.cn/api/location/city/269',
       'https://tnfcms.blue-dot.cn/api/location/city/270',
       'https://tnfcms.blue-dot.cn/api/location/city/271',
       'https://tnfcms.blue-dot.cn/api/location/city/272',
       'https://tnfcms.blue-dot.cn/api/location/city/273',
       'https://tnfcms.blue-dot.cn/api/location/city/274',
       'https://tnfcms.blue-dot.cn/api/location/city/275',
       'https://tnfcms.blue-dot.cn/api/location/city/276',
       'https://tnfcms.blue-dot.cn/api/location/city/277',
       'https://tnfcms.blue-dot.cn/api/location/city/278',
       'https://tnfcms.blue-dot.cn/api/location/city/279',
       'https://tnfcms.blue-dot.cn/api/location/city/280',
       'https://tnfcms.blue-dot.cn/api/location/city/281',
       'https://tnfcms.blue-dot.cn/api/location/city/282',
       'https://tnfcms.blue-dot.cn/api/location/city/283',
       'https://tnfcms.blue-dot.cn/api/location/city/284',
       'https://tnfcms.blue-dot.cn/api/location/city/285',
       'https://tnfcms.blue-dot.cn/api/location/city/286',
       'https://tnfcms.blue-dot.cn/api/location/city/287',
       'https://tnfcms.blue-dot.cn/api/location/city/288',
       'https://tnfcms.blue-dot.cn/api/location/city/289',
       'https://tnfcms.blue-dot.cn/api/location/city/290',
       'https://tnfcms.blue-dot.cn/api/location/city/291',
       'https://tnfcms.blue-dot.cn/api/location/city/292',
       'https://tnfcms.blue-dot.cn/api/location/city/293',
       'https://tnfcms.blue-dot.cn/api/location/city/294',
       'https://tnfcms.blue-dot.cn/api/location/city/295',
       'https://tnfcms.blue-dot.cn/api/location/city/296',
       'https://tnfcms.blue-dot.cn/api/location/city/297',
       'https://tnfcms.blue-dot.cn/api/location/city/298',
       'https://tnfcms.blue-dot.cn/api/location/city/299',
       'https://tnfcms.blue-dot.cn/api/location/city/300',
       'https://tnfcms.blue-dot.cn/api/location/city/301',
       'https://tnfcms.blue-dot.cn/api/location/city/302',
       'https://tnfcms.blue-dot.cn/api/location/city/303',
       'https://tnfcms.blue-dot.cn/api/location/city/304',
       'https://tnfcms.blue-dot.cn/api/location/city/305',
       'https://tnfcms.blue-dot.cn/api/location/city/306',
       'https://tnfcms.blue-dot.cn/api/location/city/307',
       'https://tnfcms.blue-dot.cn/api/location/city/308',
       'https://tnfcms.blue-dot.cn/api/location/city/309',
       'https://tnfcms.blue-dot.cn/api/location/city/310',
       'https://tnfcms.blue-dot.cn/api/location/city/311',
       'https://tnfcms.blue-dot.cn/api/location/city/312',
       'https://tnfcms.blue-dot.cn/api/location/city/313',
       'https://tnfcms.blue-dot.cn/api/location/city/314',
       'https://tnfcms.blue-dot.cn/api/location/city/315',
       'https://tnfcms.blue-dot.cn/api/location/city/316',
       'https://tnfcms.blue-dot.cn/api/location/city/317',
       'https://tnfcms.blue-dot.cn/api/location/city/318',
       'https://tnfcms.blue-dot.cn/api/location/city/319',
       'https://tnfcms.blue-dot.cn/api/location/city/320',
       'https://tnfcms.blue-dot.cn/api/location/city/321',
       'https://tnfcms.blue-dot.cn/api/location/city/322',
       'https://tnfcms.blue-dot.cn/api/location/city/323',
       'https://tnfcms.blue-dot.cn/api/location/city/324',
       'https://tnfcms.blue-dot.cn/api/location/city/325',
       'https://tnfcms.blue-dot.cn/api/location/city/326',
       'https://tnfcms.blue-dot.cn/api/location/city/327',
       'https://tnfcms.blue-dot.cn/api/location/city/328',
       'https://tnfcms.blue-dot.cn/api/location/city/329',
       'https://tnfcms.blue-dot.cn/api/location/city/330',
       'https://tnfcms.blue-dot.cn/api/location/city/331',
       'https://tnfcms.blue-dot.cn/api/location/city/332',
       'https://tnfcms.blue-dot.cn/api/location/city/333',
       'https://tnfcms.blue-dot.cn/api/location/city/334',
       'https://tnfcms.blue-dot.cn/api/location/city/335',
       'https://tnfcms.blue-dot.cn/api/location/city/336',
       'https://tnfcms.blue-dot.cn/api/location/city/337',
       'https://tnfcms.blue-dot.cn/api/location/city/338',
       'https://tnfcms.blue-dot.cn/api/location/city/339',
       'https://tnfcms.blue-dot.cn/api/location/city/340',
       'https://tnfcms.blue-dot.cn/api/location/city/341',
       'https://tnfcms.blue-dot.cn/api/location/city/342',
       'https://tnfcms.blue-dot.cn/api/location/city/343',
       'https://tnfcms.blue-dot.cn/api/location/city/344',
       'https://tnfcms.blue-dot.cn/api/location/city/345',
       'https://tnfcms.blue-dot.cn/api/location/city/346',
       'https://tnfcms.blue-dot.cn/api/location/city/347',
       'https://tnfcms.blue-dot.cn/api/location/city/348',
       'https://tnfcms.blue-dot.cn/api/location/city/349',
       'https://tnfcms.blue-dot.cn/api/location/city/350',
       'https://tnfcms.blue-dot.cn/api/location/city/351',
       'https://tnfcms.blue-dot.cn/api/location/city/352',
       'https://tnfcms.blue-dot.cn/api/location/city/353',
       'https://tnfcms.blue-dot.cn/api/location/city/354',
       'https://tnfcms.blue-dot.cn/api/location/city/355',
       'https://tnfcms.blue-dot.cn/api/location/city/356',
       'https://tnfcms.blue-dot.cn/api/location/city/357',
       'https://tnfcms.blue-dot.cn/api/location/city/358',
       'https://tnfcms.blue-dot.cn/api/location/city/359',
       'https://tnfcms.blue-dot.cn/api/location/city/360',
       'https://tnfcms.blue-dot.cn/api/location/city/361',
       'https://tnfcms.blue-dot.cn/api/location/city/362',
       'https://tnfcms.blue-dot.cn/api/location/city/363',
       'https://tnfcms.blue-dot.cn/api/location/city/364',
       'https://tnfcms.blue-dot.cn/api/location/city/365',
       'https://tnfcms.blue-dot.cn/api/location/city/366',
       'https://tnfcms.blue-dot.cn/api/location/city/367',
       'https://tnfcms.blue-dot.cn/api/location/city/368',
       'https://tnfcms.blue-dot.cn/api/location/city/369',
       'https://tnfcms.blue-dot.cn/api/location/city/370',
       'https://tnfcms.blue-dot.cn/api/location/city/371',
       'https://tnfcms.blue-dot.cn/api/location/city/372',
       'https://tnfcms.blue-dot.cn/api/location/city/373',
       'https://tnfcms.blue-dot.cn/api/location/city/374',
       'https://tnfcms.blue-dot.cn/api/location/city/375',
       'https://tnfcms.blue-dot.cn/api/location/city/376',
       'https://tnfcms.blue-dot.cn/api/location/city/377',
       'https://tnfcms.blue-dot.cn/api/location/city/378',
       'https://tnfcms.blue-dot.cn/api/location/city/379',
       'https://tnfcms.blue-dot.cn/api/location/city/380',
       'https://tnfcms.blue-dot.cn/api/location/city/381',
       'https://tnfcms.blue-dot.cn/api/location/city/382',
       'https://tnfcms.blue-dot.cn/api/location/city/383',
       'https://tnfcms.blue-dot.cn/api/location/city/384',
       'https://tnfcms.blue-dot.cn/api/location/city/385',
       'https://tnfcms.blue-dot.cn/api/location/city/386',
       'https://tnfcms.blue-dot.cn/api/location/city/387',
       'https://tnfcms.blue-dot.cn/api/location/city/388',
       'https://tnfcms.blue-dot.cn/api/location/city/389',
       'https://tnfcms.blue-dot.cn/api/location/city/390',
       'https://tnfcms.blue-dot.cn/api/location/city/391',
       'https://tnfcms.blue-dot.cn/api/location/city/392',
       'https://tnfcms.blue-dot.cn/api/location/city/393',
       'https://tnfcms.blue-dot.cn/api/location/city/394',
       'https://tnfcms.blue-dot.cn/api/location/city/395',
       'https://tnfcms.blue-dot.cn/api/location/city/396',
       'https://tnfcms.blue-dot.cn/api/location/city/397',
       'https://tnfcms.blue-dot.cn/api/location/city/398',
       'https://tnfcms.blue-dot.cn/api/location/city/399',
       'https://tnfcms.blue-dot.cn/api/location/city/400',
       'https://tnfcms.blue-dot.cn/api/location/city/401',
       'https://tnfcms.blue-dot.cn/api/location/city/402',
       'https://tnfcms.blue-dot.cn/api/location/city/403',
       'https://tnfcms.blue-dot.cn/api/location/city/404',
       'https://tnfcms.blue-dot.cn/api/location/city/405',
       'https://tnfcms.blue-dot.cn/api/location/city/406',
       'https://tnfcms.blue-dot.cn/api/location/city/407',
       'https://tnfcms.blue-dot.cn/api/location/city/408',
       'https://tnfcms.blue-dot.cn/api/location/city/409',
       'https://tnfcms.blue-dot.cn/api/location/city/410',
       'https://tnfcms.blue-dot.cn/api/location/city/411',
       'https://tnfcms.blue-dot.cn/api/location/city/412',
       'https://tnfcms.blue-dot.cn/api/location/city/413',
       'https://tnfcms.blue-dot.cn/api/location/city/414',
       'https://tnfcms.blue-dot.cn/api/location/city/415',
       'https://tnfcms.blue-dot.cn/api/location/city/416',
       'https://tnfcms.blue-dot.cn/api/location/city/417',
       'https://tnfcms.blue-dot.cn/api/location/city/418',
       'https://tnfcms.blue-dot.cn/api/location/city/419',
       'https://tnfcms.blue-dot.cn/api/location/city/420',
       'https://tnfcms.blue-dot.cn/api/location/city/421',
       'https://tnfcms.blue-dot.cn/api/location/city/422',
       'https://tnfcms.blue-dot.cn/api/location/city/423',
       'https://tnfcms.blue-dot.cn/api/location/city/424',
       'https://tnfcms.blue-dot.cn/api/location/city/425',
       'https://tnfcms.blue-dot.cn/api/location/city/426',
       'https://tnfcms.blue-dot.cn/api/location/city/427',
       'https://tnfcms.blue-dot.cn/api/location/city/428',
       'https://tnfcms.blue-dot.cn/api/location/city/429',
       'https://tnfcms.blue-dot.cn/api/location/city/430',
       'https://tnfcms.blue-dot.cn/api/location/city/431',
       'https://tnfcms.blue-dot.cn/api/location/city/432',
       'https://tnfcms.blue-dot.cn/api/location/city/433',
       'https://tnfcms.blue-dot.cn/api/location/city/434',
       'https://tnfcms.blue-dot.cn/api/location/city/435',
       'https://tnfcms.blue-dot.cn/api/location/city/436',
       'https://tnfcms.blue-dot.cn/api/location/city/437',
       'https://tnfcms.blue-dot.cn/api/location/city/438',
       'https://tnfcms.blue-dot.cn/api/location/city/439',
       'https://tnfcms.blue-dot.cn/api/location/city/440',
       'https://tnfcms.blue-dot.cn/api/location/city/441',
       'https://tnfcms.blue-dot.cn/api/location/city/442',
       'https://tnfcms.blue-dot.cn/api/location/city/443',
       'https://tnfcms.blue-dot.cn/api/location/city/444',
       'https://tnfcms.blue-dot.cn/api/location/city/445',
       'https://tnfcms.blue-dot.cn/api/location/city/446',
       'https://tnfcms.blue-dot.cn/api/location/city/447',
       'https://tnfcms.blue-dot.cn/api/location/city/448',
       'https://tnfcms.blue-dot.cn/api/location/city/449',
       'https://tnfcms.blue-dot.cn/api/location/city/450',
       'https://tnfcms.blue-dot.cn/api/location/city/451',
       'https://tnfcms.blue-dot.cn/api/location/city/452',
       'https://tnfcms.blue-dot.cn/api/location/city/453',
       'https://tnfcms.blue-dot.cn/api/location/city/454',
       'https://tnfcms.blue-dot.cn/api/location/city/455',
       'https://tnfcms.blue-dot.cn/api/location/city/456',
       'https://tnfcms.blue-dot.cn/api/location/city/457',
       'https://tnfcms.blue-dot.cn/api/location/city/458',
       'https://tnfcms.blue-dot.cn/api/location/city/459',
       'https://tnfcms.blue-dot.cn/api/location/city/460',
       'https://tnfcms.blue-dot.cn/api/location/city/461',
       'https://tnfcms.blue-dot.cn/api/location/city/462',
       'https://tnfcms.blue-dot.cn/api/location/city/463',
       'https://tnfcms.blue-dot.cn/api/location/city/464',
       'https://tnfcms.blue-dot.cn/api/location/city/465',
       'https://tnfcms.blue-dot.cn/api/location/city/466',
       'https://tnfcms.blue-dot.cn/api/location/city/467',
       'https://tnfcms.blue-dot.cn/api/location/city/468',
       'https://tnfcms.blue-dot.cn/api/location/city/469',
       'https://tnfcms.blue-dot.cn/api/location/city/470',
       'https://tnfcms.blue-dot.cn/api/location/city/471',
       'https://tnfcms.blue-dot.cn/api/location/city/472',
       'https://tnfcms.blue-dot.cn/api/location/city/473',
       'https://tnfcms.blue-dot.cn/api/location/city/474',
       'https://tnfcms.blue-dot.cn/api/location/city/475',
       'https://tnfcms.blue-dot.cn/api/location/city/476',
       'https://tnfcms.blue-dot.cn/api/location/city/477',
       'https://tnfcms.blue-dot.cn/api/location/city/478',
       'https://tnfcms.blue-dot.cn/api/location/city/479',
       'https://tnfcms.blue-dot.cn/api/location/city/480',
       'https://tnfcms.blue-dot.cn/api/location/city/481',
       'https://tnfcms.blue-dot.cn/api/location/city/482',
       'https://tnfcms.blue-dot.cn/api/location/city/483',
       'https://tnfcms.blue-dot.cn/api/location/city/484',
       'https://tnfcms.blue-dot.cn/api/location/city/485',
       'https://tnfcms.blue-dot.cn/api/location/city/486',
       'https://tnfcms.blue-dot.cn/api/location/city/487',
       'https://tnfcms.blue-dot.cn/api/location/city/488',
       'https://tnfcms.blue-dot.cn/api/location/city/489',
       'https://tnfcms.blue-dot.cn/api/location/city/490',
       'https://tnfcms.blue-dot.cn/api/location/city/491',
       'https://tnfcms.blue-dot.cn/api/location/city/492',
       'https://tnfcms.blue-dot.cn/api/location/city/493',
       'https://tnfcms.blue-dot.cn/api/location/city/494',
       'https://tnfcms.blue-dot.cn/api/location/city/495',
       'https://tnfcms.blue-dot.cn/api/location/city/496',
       'https://tnfcms.blue-dot.cn/api/location/city/497',
       'https://tnfcms.blue-dot.cn/api/location/city/498',
       'https://tnfcms.blue-dot.cn/api/location/city/499',
       'https://tnfcms.blue-dot.cn/api/location/city/500',
       'https://tnfcms.blue-dot.cn/api/location/city/501',
       'https://tnfcms.blue-dot.cn/api/location/city/502',
       'https://tnfcms.blue-dot.cn/api/location/city/503',
       'https://tnfcms.blue-dot.cn/api/location/city/504',
       'https://tnfcms.blue-dot.cn/api/location/city/505',
       'https://tnfcms.blue-dot.cn/api/location/city/506',
       'https://tnfcms.blue-dot.cn/api/location/city/507',
       'https://tnfcms.blue-dot.cn/api/location/city/508',
       'https://tnfcms.blue-dot.cn/api/location/city/509',
       'https://tnfcms.blue-dot.cn/api/location/city/510',
       'https://tnfcms.blue-dot.cn/api/location/city/511',
       'https://tnfcms.blue-dot.cn/api/location/city/512',
       'https://tnfcms.blue-dot.cn/api/location/city/513',
       'https://tnfcms.blue-dot.cn/api/location/city/514',
       'https://tnfcms.blue-dot.cn/api/location/city/515',
       'https://tnfcms.blue-dot.cn/api/location/city/516',
       'https://tnfcms.blue-dot.cn/api/location/city/517',
       'https://tnfcms.blue-dot.cn/api/location/city/518',
       'https://tnfcms.blue-dot.cn/api/location/city/519',
       'https://tnfcms.blue-dot.cn/api/location/city/520',
       'https://tnfcms.blue-dot.cn/api/location/city/521',
       'https://tnfcms.blue-dot.cn/api/location/city/522',
       'https://tnfcms.blue-dot.cn/api/location/city/523',
       'https://tnfcms.blue-dot.cn/api/location/city/524',
       'https://tnfcms.blue-dot.cn/api/location/city/525',
       'https://tnfcms.blue-dot.cn/api/location/city/526',
       'https://tnfcms.blue-dot.cn/api/location/city/527',
       'https://tnfcms.blue-dot.cn/api/location/city/528',
       'https://tnfcms.blue-dot.cn/api/location/city/529',
       'https://tnfcms.blue-dot.cn/api/location/city/530',
       'https://tnfcms.blue-dot.cn/api/location/city/531',
       'https://tnfcms.blue-dot.cn/api/location/city/532',
       'https://tnfcms.blue-dot.cn/api/location/city/533',
       'https://tnfcms.blue-dot.cn/api/location/city/534',
       'https://tnfcms.blue-dot.cn/api/location/city/535',
       'https://tnfcms.blue-dot.cn/api/location/city/536',
       'https://tnfcms.blue-dot.cn/api/location/city/537',
       'https://tnfcms.blue-dot.cn/api/location/city/538',
       'https://tnfcms.blue-dot.cn/api/location/city/539',
       'https://tnfcms.blue-dot.cn/api/location/city/540',
       'https://tnfcms.blue-dot.cn/api/location/city/541',
       'https://tnfcms.blue-dot.cn/api/location/city/542',
       'https://tnfcms.blue-dot.cn/api/location/city/543',
       'https://tnfcms.blue-dot.cn/api/location/city/544',
       'https://tnfcms.blue-dot.cn/api/location/city/545',
       'https://tnfcms.blue-dot.cn/api/location/city/546',
       'https://tnfcms.blue-dot.cn/api/location/city/547',
       'https://tnfcms.blue-dot.cn/api/location/city/548',
       'https://tnfcms.blue-dot.cn/api/location/city/549',
       'https://tnfcms.blue-dot.cn/api/location/city/550',
       'https://tnfcms.blue-dot.cn/api/location/city/551',
       'https://tnfcms.blue-dot.cn/api/location/city/552',
       'https://tnfcms.blue-dot.cn/api/location/city/553',
       'https://tnfcms.blue-dot.cn/api/location/city/554',
       'https://tnfcms.blue-dot.cn/api/location/city/555',
       'https://tnfcms.blue-dot.cn/api/location/city/556',
       'https://tnfcms.blue-dot.cn/api/location/city/557',
       'https://tnfcms.blue-dot.cn/api/location/city/558',
       'https://tnfcms.blue-dot.cn/api/location/city/559',
       'https://tnfcms.blue-dot.cn/api/location/city/560',
       'https://tnfcms.blue-dot.cn/api/location/city/561',
       'https://tnfcms.blue-dot.cn/api/location/city/562',
       'https://tnfcms.blue-dot.cn/api/location/city/563',
       'https://tnfcms.blue-dot.cn/api/location/city/564',
       'https://tnfcms.blue-dot.cn/api/location/city/565',
       'https://tnfcms.blue-dot.cn/api/location/city/566',
       'https://tnfcms.blue-dot.cn/api/location/city/567',
       'https://tnfcms.blue-dot.cn/api/location/city/568',
       'https://tnfcms.blue-dot.cn/api/location/city/569',
       'https://tnfcms.blue-dot.cn/api/location/city/570',
       'https://tnfcms.blue-dot.cn/api/location/city/571',
       'https://tnfcms.blue-dot.cn/api/location/city/572',
       'https://tnfcms.blue-dot.cn/api/location/city/573',
       'https://tnfcms.blue-dot.cn/api/location/city/574',
       'https://tnfcms.blue-dot.cn/api/location/city/575',
       'https://tnfcms.blue-dot.cn/api/location/city/576',
       'https://tnfcms.blue-dot.cn/api/location/city/577',
       'https://tnfcms.blue-dot.cn/api/location/city/578',
       'https://tnfcms.blue-dot.cn/api/location/city/579',
       'https://tnfcms.blue-dot.cn/api/location/city/580',
       'https://tnfcms.blue-dot.cn/api/location/city/581',
       'https://tnfcms.blue-dot.cn/api/location/city/582',
       'https://tnfcms.blue-dot.cn/api/location/city/583',
       'https://tnfcms.blue-dot.cn/api/location/city/584',
       'https://tnfcms.blue-dot.cn/api/location/city/585',
       'https://tnfcms.blue-dot.cn/api/location/city/586',
       'https://tnfcms.blue-dot.cn/api/location/city/587',
       'https://tnfcms.blue-dot.cn/api/location/city/588',
       'https://tnfcms.blue-dot.cn/api/location/city/589',
       'https://tnfcms.blue-dot.cn/api/location/city/590',
       'https://tnfcms.blue-dot.cn/api/location/city/591',
       'https://tnfcms.blue-dot.cn/api/location/city/592',
       'https://tnfcms.blue-dot.cn/api/location/city/593',
       'https://tnfcms.blue-dot.cn/api/location/city/594',
       'https://tnfcms.blue-dot.cn/api/location/city/595',
       'https://tnfcms.blue-dot.cn/api/location/city/596',
       'https://tnfcms.blue-dot.cn/api/location/city/597',
       'https://tnfcms.blue-dot.cn/api/location/city/598',
       'https://tnfcms.blue-dot.cn/api/location/city/599',
       'https://tnfcms.blue-dot.cn/api/location/city/600',
       'https://tnfcms.blue-dot.cn/api/location/city/601',
       'https://tnfcms.blue-dot.cn/api/location/city/602',
       'https://tnfcms.blue-dot.cn/api/location/city/603',
       'https://tnfcms.blue-dot.cn/api/location/city/604',
       'https://tnfcms.blue-dot.cn/api/location/city/605',
       'https://tnfcms.blue-dot.cn/api/location/city/606',
       'https://tnfcms.blue-dot.cn/api/location/city/607',
       'https://tnfcms.blue-dot.cn/api/location/city/608',
       'https://tnfcms.blue-dot.cn/api/location/city/609',
       'https://tnfcms.blue-dot.cn/api/location/city/610',
       'https://tnfcms.blue-dot.cn/api/location/city/611',
       'https://tnfcms.blue-dot.cn/api/location/city/612',
       'https://tnfcms.blue-dot.cn/api/location/city/613',
       'https://tnfcms.blue-dot.cn/api/location/city/614',
       'https://tnfcms.blue-dot.cn/api/location/city/615',
       'https://tnfcms.blue-dot.cn/api/location/city/616',
       'https://tnfcms.blue-dot.cn/api/location/city/617',
       'https://tnfcms.blue-dot.cn/api/location/city/618',
       'https://tnfcms.blue-dot.cn/api/location/city/619',
       'https://tnfcms.blue-dot.cn/api/location/city/620',
       'https://tnfcms.blue-dot.cn/api/location/city/621',
       'https://tnfcms.blue-dot.cn/api/location/city/622',
       'https://tnfcms.blue-dot.cn/api/location/city/623',
       'https://tnfcms.blue-dot.cn/api/location/city/624',
       'https://tnfcms.blue-dot.cn/api/location/city/625',
       'https://tnfcms.blue-dot.cn/api/location/city/626',
       'https://tnfcms.blue-dot.cn/api/location/city/627',
       'https://tnfcms.blue-dot.cn/api/location/city/628',
       'https://tnfcms.blue-dot.cn/api/location/city/629',
       'https://tnfcms.blue-dot.cn/api/location/city/630',
       'https://tnfcms.blue-dot.cn/api/location/city/631',
       'https://tnfcms.blue-dot.cn/api/location/city/632',
       'https://tnfcms.blue-dot.cn/api/location/city/633',
       'https://tnfcms.blue-dot.cn/api/location/city/634',
       'https://tnfcms.blue-dot.cn/api/location/city/635',
       'https://tnfcms.blue-dot.cn/api/location/city/636',
       'https://tnfcms.blue-dot.cn/api/location/city/637',
       'https://tnfcms.blue-dot.cn/api/location/city/638',
       'https://tnfcms.blue-dot.cn/api/location/city/639',
       'https://tnfcms.blue-dot.cn/api/location/city/640',
       'https://tnfcms.blue-dot.cn/api/location/city/641',
       'https://tnfcms.blue-dot.cn/api/location/city/642',
       'https://tnfcms.blue-dot.cn/api/location/city/643',
       'https://tnfcms.blue-dot.cn/api/location/city/644',
       'https://tnfcms.blue-dot.cn/api/location/city/645',
       'https://tnfcms.blue-dot.cn/api/location/city/646',
       'https://tnfcms.blue-dot.cn/api/location/city/647',
       'https://tnfcms.blue-dot.cn/api/location/city/648',
       'https://tnfcms.blue-dot.cn/api/location/city/649',
       'https://tnfcms.blue-dot.cn/api/location/city/650',
       ]

f = open('the_north_face.csv', "w+", encoding="utf-8")
title = []
title.append('sel')
for u in url:
    html = download5(u)
    # sleep(5)
    html = json.loads(html)
    if html['data'] is not None:

        s = html['data']
        print(s)
        for i in s:
            f.write(u)
            f.write(',')
            for k in i.keys():

                if k not in title:
                    title.append(k)
                    f.write(k)
                    f.write(',')
            f.write('\n')
            print(title)
            break
        print(title)
        for i in s:
            for t in title:
                for k, v in i.items():
                    if k == t:
                        f.write(str(v))
                        f.write(',')
            f.write('\n')
f.close()
